// This file is generated by Slice Machine. Update with care!

import Guides from './Guides';
import Hero from './Hero';
import ReversableSection from './ReversableSection';
import Testimonials from './Testimonials';

export {
	Guides,
	Hero,
	ReversableSection,
	Testimonials,
};

export const components = {
	guides: Guides,
	hero: Hero,
	reversable_section: ReversableSection,
	testimonials: Testimonials,
};
